### ISSUE TITLE
allow to override decimal separator

### ISSUE THREAD

**Issue by kmike** [scrapinghub/price-parser#15]
Sometimes values like 140.000 can mean 140, not 140K; this happens when e.g. website authors put price in semantic markup with 3 digit precision. It looks like the only way to fix it is to allow customizing price extraction; e.g. it can be fixed by having "decimal_separator_hint" argument for price parsing functions, which one can pass for these "bad" websites.

**Comment by WinterComes** [comment]
Hello. I added "decimal_separator_hint" logic, described above, and tests. Could you review this PR, please? Thanks

**Comment by kmike** [comment]
Fixed by #18 - thanks @WinterComes, and sorry for a delayed review!
