### ISSUE TITLE
Getting error while installing the price-parser

### ISSUE THREAD

**Issue by rpalsaxena** [scrapinghub/price-parser#25]
I wanted to contribute to this repo. Tried to install it manually using the `python setup.py develop` and `python setup.py` commands but it gave me errors.

![image](https://user-images.githubusercontent.com/8288236/71173875-de14f200-2289-11ea-8987-bd02a1bbf276.png)

**Comment by rpalsaxena** [comment]
I resolved this issue by making an edit in the setup.py. It works correctly on Linux OS. The error seems to occur only on Windows machine. 

It got resolved by adding `encoding="utf8"` parameter.

```
    long_description=open('README.rst', encoding="utf8").read() + "\n\n" + open('CHANGES.rst').read(),
```

**Comment by lopuhin** [comment]
Thanks for investigating @rpalsaxena . Would you like to send a pull request with this fix?

**Comment by rpalsaxena** [comment]
I have sent a pull request but there's another issue that I'm facing while importing it. 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\rpals\Desktop\price-parser\price_parser\__init__.py", line 2, in <module>
    from .parser import Price, parse_price
  File "C:\Users\rpals\Desktop\price-parser\price_parser\parser.py", line 14
    amount: Optional[Decimal]   # price numeric value, as Decimal
          ^
SyntaxError: invalid syntax
```

**Comment by lopuhin** [comment]
This error seems to originate from a python version mismatch - priceparser requires python 3.6 or newer

**Comment by rpalsaxena** [comment]
You're right @lopuhin ! :)
