### ISSUE TITLE
Feature update to convert from one currency to another

### ISSUE THREAD

**Issue by debdutgoswami** [scrapinghub/price-parser#34]
Currently the `price-parser` library  call only extract prices and store them with it's  currency tag. I would like to propose the ability of converting one price to another. If this proposal is approved I would start working on the idea.

**Comment by Gallaecio** [comment]
I’m not sure this falls within the scope of price-parser. And there seem to be already projects covering this use case, which can be used together with price-parser if desired, such as https://pypi.org/project/CurrencyConverter/.

**Comment by debdutgoswami** [comment]
Okay got it. Thanks for clarifying.
