### ISSUE TITLE
Wrong currency extracted in case of long strings containing "$"

### ISSUE THREAD

**Issue by croqaz** [scrapinghub/price-parser#48]
These examples:

```py
Price.fromstring('180', currency_hint='$${product.price.currency}')
Price.fromstring('180', currency_hint='qwerty $')
Price.fromstring('180', currency_hint='qwerty $ asdfg')
```

All of them return `Price(amount=Decimal('180'), currency='$')`.

From what I understand in the code, this happens in `_search_safe_currency`:

```py
_search_unsafe_currency('asd $ qwe')
# <re.Match object; match='$'>
```

Would it be in the scope of the library to match the currency more strictly?
This would cover the use-case when we are pretty sure that the currency hint is exact, not fuzzy.

**Comment by Gallaecio** [comment]
I’m personally not sure this is something price-number should aim to address. It feels to me like the code calling price-parser here should be responsible of cleaning up what it passes to `currentcy_hint` before it is passed.

**Comment by croqaz** [comment]
Makes sense. We will see what we can do.
I think it's safe to close for now.

**Comment by lopuhin** [comment]
> It feels to me like the code calling price-parser here should be responsible of cleaning up what it passes to currentcy_hint before it is passed.

But then maybe price-parser shouldn't alter the original currency?

**Comment by Gallaecio** [comment]
> But then maybe price-parser shouldn't alter the original currency?

I’m not sure that’s happening here, at least in the examples from the issue description, where there’s only the currency hint being passed, no original currency is specified otherwise.

**Comment by lopuhin** [comment]
Sure, let us look a bit more into it and then we can decide if the fix makes sense in the context of price-parser.
