### ISSUE TITLE
Migrate CI to github actions

### ISSUE THREAD

**Issue by kmike** [scrapinghub/price-parser#52]
Currently CI looks broken, it is not running on pull requests.

**Comment by Gallaecio** [comment]
[There](https://github.com/scrapy/parsel/tree/master/.github/workflows) [are](https://github.com/scrapy/cssselect/tree/master/.github/workflows) [quite](https://github.com/scrapy/protego/tree/master/.github/workflows) [a](https://github.com/scrapy/xtractmime/tree/main/.github/workflows) [few](https://github.com/scrapy/itemadapter/tree/master/.github/workflows) [examples](https://github.com/scrapy/itemloaders/tree/master/.github/workflows) [to](https://github.com/scrapinghub/spidermon/tree/master/.github/workflows) take inspiration from.

**Comment by ivsanro1** [comment]
Closing this, as it's fixed by https://github.com/scrapinghub/price-parser/pull/55 which is already merged :)
